import { chromium } from 'playwright';
const OUT = new URL('./out/', import.meta.url).pathname;
const b = await chromium.launch(); const p = await b.newPage({ viewport: { width: 1100, height: 900 } });
const shot = async (n: string) => { await p.screenshot({ path: `${OUT}landing-video-${n}.png`, fullPage: true }); console.log(new Date().toLocaleTimeString('en-US', { hour12: false }), 'shot', n); };
await p.goto('http://localhost:4710/?site=main&suffix=LV');
for (const n of ['referral-01.pdf', 'referral-02.pdf', 'referral-03.pdf']) await p.uncheck(`input[value="${n}"]`);
await p.check('input[value="referral-06.pdf"]');
await p.setInputFiles('#video', '<repo>/submission/recordings/referral-demo-splitscreen-v1.mp4');
await shot('1-form');
await p.click('#go');
await p.waitForSelector('#s-understand.ok'); await shot('2-understand');
console.log('STEP1 TEXT >>>\n' + await p.locator('#s-understand').innerText() + '\n<<<');
await p.waitForSelector('#s-login.ok, #s-login.bad', { timeout: 60000 }); await shot('3-login');
console.log('login:', await p.locator('#s-login .st').innerText());
await p.waitForSelector('#s-run .st:has-text("running")', { timeout: 60000 }).catch(() => {}); await shot('4-running');
await p.waitForSelector('#s-run.ok, #s-run.bad', { timeout: 600000 }); await p.waitForTimeout(3000); await shot('5-confirm');
console.log('RUN >>> ' + await p.locator('#s-run').innerText());
await p.locator('#s-take').scrollIntoViewIfNeeded(); await shot('6-take-it-with-you');
await b.close();
